name: Sync ghcr.io/loong64/buildkit

on:
  push:
  schedule:
    - cron: '23 7 * * 2'
  workflow_dispatch:
    inputs:
      source_image:
        description: 'source image (e.g. ghcr.io/loong64/buildkit)'
        required: true
        type: string
        default: 'ghcr.io/loong64/buildkit'
      source_tag:
        description: 'source image tag'
        required: true
        type: string
        default: 'buildx-stable-1'
      target_name:
        description: 'target image name'
        required: false
        type: string
        default: 'loong64-buildkit'

env:
  NAMESPACE: ${{ vars.NAMESPACE || 'kubernetesloong64' }}
  SOURCE_IMAGE: ${{ inputs.source_image || 'ghcr.io/loong64/buildkit' }}
  SOURCE_TAG: ${{ inputs.source_tag || 'buildx-stable-1' }}
  TARGET_NAME: ${{ inputs.target_name || 'loong64-buildkit' }}

jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      platform: ${{ steps.platform.outputs.platform }}
    steps:
      - name: docker info
        run: docker info

      - name: platform
        id: platform
        run: |
          IMAGE="${{ env.SOURCE_IMAGE }}:${{ env.SOURCE_TAG }}"
          PLATFORM=$(docker manifest inspect "$IMAGE" | jq -rc 'if .manifests then [.manifests[].platform.architecture | select(. != "unknown")] else ["amd64"] end')
          echo "platform=$PLATFORM"
          echo "platform=$PLATFORM" >> $GITHUB_OUTPUT

  build:
    needs: matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform: ${{ fromJson(needs.matrix.outputs.platform) }}

    steps:
      - name: docker login ${{ vars.SYNC_REGISTRY }}
        run: |
          echo "${{ secrets.SYNC_REGISTRY_PASSWORD }}" | docker login "${{ vars.SYNC_REGISTRY }}" --username "${{ vars.SYNC_REGISTRY_USERNAME }}" --password-stdin

      - name: env
        run: |
          IMAGE="${{ env.SOURCE_IMAGE }}:${{ env.SOURCE_TAG }}"
          TARGET_IMAGE="${{ vars.SYNC_REGISTRY }}/${{ env.NAMESPACE }}/${{ env.TARGET_NAME }}:${{ env.SOURCE_TAG }}"

          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
          echo "TARGET_IMAGE=$TARGET_IMAGE" >> $GITHUB_ENV

      - name: docker pull ${{ matrix.platform }}
        run: |
          docker images
          docker pull --platform=linux/${{ matrix.platform }} "$IMAGE"
          docker images

      - name: docker tag
        run: |
          docker tag "$IMAGE" "$TARGET_IMAGE-${{ matrix.platform }}"
          docker images

      - name: docker push
        run: |
          docker push "$TARGET_IMAGE-${{ matrix.platform }}"

  merge:
    needs: [ matrix, build ]
    runs-on: ubuntu-latest
    steps:
      - name: docker login ${{ vars.SYNC_REGISTRY }}
        run: |
          echo "${{ secrets.SYNC_REGISTRY_PASSWORD }}" | docker login "${{ vars.SYNC_REGISTRY }}" --username "${{ vars.SYNC_REGISTRY_USERNAME }}" --password-stdin

      - name: env
        run: |
          TARGET_IMAGE="${{ vars.SYNC_REGISTRY }}/${{ env.NAMESPACE }}/${{ env.TARGET_NAME }}:${{ env.SOURCE_TAG }}"

          echo "TARGET_IMAGE=$TARGET_IMAGE" >> $GITHUB_ENV

      - name: docker manifest create
        run: |
          IMAGES=""
          for arch in $(echo '${{ needs.matrix.outputs.platform }}' | jq -r '.[]'); do
            IMAGES="$IMAGES $TARGET_IMAGE-$arch"
          done
          docker manifest create $TARGET_IMAGE $IMAGES

      - name: docker manifest push
        run: |
          docker manifest push "$TARGET_IMAGE"
